# Generated by Django 4.2.4 on 2023-08-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_0010_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitygroup',
            name='membership_type',
            field=models.CharField(choices=[('UNION', 'Union'), ('INTERSECTION', 'Intersection')], default='UNION'),
        ),
    ]
