# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 19:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_allentityproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
