# Generated by Django 4.2.4 on 2023-08-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_auto_20181213_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitygroup',
            name='logic_string',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
