# Generated by Django 4.2.5 on 2023-09-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0011_entitygroup_logic_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitygroupmembership',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
